{
    'name': 'Artec Collect',
    'version': '18.0.1.0.0',
    'description': 'Artec Collect',
    'author': 'SARL ARTEC-INT',
    'website': 'www.artec-int.com',
    'license': 'LGPL-3',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/artec_strapping_sequence.xml',
        'data/artec_product_data.xml',
        'views/artec_tank_views.xml',
        'views/artec_product_views.xml',
        'views/artec_strapping_views.xml',
        'views/artec_gauging_views.xml',
        'views/artec_astm_views.xml',
        'views/artec_expedition_views.xml',
        'views/artec_production_views.xml',
        'wizard/artec_tank_expedition_report_wizard_view.xml',
        'wizard/artec_tank_production_report_wizard_view.xml',
        'wizard/artec_expedition_report_wizard_view.xml',
        'wizard/artec_production_report_wizard_view.xml',
        'report/artec_tank_expedition_report.xml',
        'report/artec_tank_production_report.xml',
        'views/menus.xml',
    ],
    'depends':[
        'base',
        'web'
    ],
    'auto_install': True,
    'application': True,
}